### ISSUE TITLE
Possible drawback to be aware of?

### ISSUE THREAD

**Issue by yellow1912** [lukeed/ganalytics#15]
Thank you for the hard work you put in this fantastic module. Given that this one is tiny compared to the original module by google, is there any limitations that we should be aware of when using it? Or is it just that google team is really bad at writing code?

**Comment by lukeed** [comment]
Hi, thank you!

No, they're not terrible at all. The difference is that `ga.js` does a lot
of setup and tracking for you automatically. Here, almost nothing is
automatic, so you have to set up the parameters you're interested in
collecting. The REST API still fills in quite a bit for you via HTTP
headers (recommend you play with the dashboard to see what's coming in)
but, if you look at the Google Docs, there's a _lottttt_ of parameters and
parameter groups. The `ga.js` is prepared for all of that, even if you
never use it.

Also, I think GTM requires/piggybacks off of `ga.js` – although I'm not
100% sure anymore.

Hope that helps!
