### ISSUE TITLE
Replace with Object.assign

### ISSUE THREAD

**Issue by lukeed** [lukeed/ganalytics#2]
Replace the inline `assign` helper with `Object.assign`

PRO

- Bundlers can inject replacement
- Shave Bytes

CON

- Lose IE support out of the box
  - likely affect UMD entry only

Reference: https://github.com/kristoferbaxter/preact-hn/issues/16

**Comment by xtuc** [comment]
If you use the spread operator with the Babel plugin it already injects a polyfill of Object.assign.

**Comment by lukeed** [comment]
Right, but I think most people already have `transform-object-assign` in use. Plus, if I'm going to open the door to builders, I want to be Bublé-friendly, too -- which also will recognize `Object.assign` as written.

**Comment by lukeed** [comment]
Closed in 43f87b8
