### ISSUE TITLE
user id tracking?

### ISSUE THREAD

**Issue by hallcyon11** [lukeed/ganalytics#8]
I need to set userId at the top of all my pages.

`ga('set', 'userId', hashedUsername)`

Can I do that with this module, it works perfectly for everything else. Thank you!

**Comment by hallcyon11** [comment]
https://support.google.com/analytics/answer/3123666

I have to set the userId at the top of my scripts before sending page views, events, etc so that I can more accurately track logged in users.

**Comment by lukeed** [comment]
Ah thanks, forgot about that for a second.

You have two options:

1) Initialize with custom opts (2nd param) passing in a custom [`uid`](https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#uid).

2) Set the `localStorage` key manually, found at the top of the file. I'm on phone right now and can't easily link, sorry.

I can't remember if `cid` and `uid` work alongside each other, so you might need to go with option two.

**Comment by hallcyon11** [comment]
Thank you that worked!
